### ISSUE TITLE
uninitialized constant Calculator::PriceBucket (NameError)

### ISSUE THREAD

**Issue by handcrab** [ohmycto/synergy#21]
Здравствуйте,

Ошибка при попытке установить synergy **0.70**:

```
rails g spree:site
/home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/bundler/gems/synergy-63e1cdc687a3/lib/synergy.rb:89:in `block in <class:Engine>': uninitialized constant Calculator::PriceBucket (NameError)
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `run'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `each'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/application.rb:96:in `initialize!'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/handcrab/_projects/synergy_app7/config/environment.rb:5:in `<top (required)>'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/application.rb:83:in `require_environment!'
    from /home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/gems/railties-3.1.3/lib/rails/commands.rb:22:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Gemfile:

```
gem 'rails', '3.1.3'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'mysql2', '~> 0.3.11'
gem 'active_reload'
gem 'synergy', '~> 0.70.0.beta', :git => 'git://github.com/secoint/synergy.git'
gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git'
gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git', :branch => '0-70-stable'
```

**Comment by pirj** [comment]
+1

**Comment by Mikke** [comment]
+
upd: as fastest way cut this method (PriceBucket) from file on your gemset (/home/handcrab/.rvm/gems/ruby-1.9.2-p290@rails31/bundler/gems/synergy-63e1cdc687a3/lib/synergy.rb:89)
